LABELS_TO_IDS = {
    "n": 0,
    "x": 1,
    "h": 2,
    "a": 3,
    "c": 4,
    "s": 5,
    "u": 6,
    "d": 7,
    "o": 8,
    "f": 9,
}

TRAIN_DEFAULT_SETTINGS = {
    'train_labels_path' : './labels/training_labels.tsv',
    'train_data_dir' : '/home/usuaris/veussd/federico.costa/datasets/msp_podcast/Audios/audio_files',
    'validation_labels_path' : './labels/development_labels.tsv',
    'validation_data_dir' : '/home/usuaris/veussd/federico.costa/datasets/msp_podcast/Audios/audio_files',
    'model_output_folder' : './models/',
    'log_file_folder' : './logs/train/',
    'max_epochs' : 100,
    'training_batch_size' : 64,
    'evaluation_batch_size' : 1,
    'eval_and_save_best_model_every' : 1000,
    'print_training_info_every' : 100,
    'early_stopping' : 25,
    'update_optimizer_every' : 10,
    'load_checkpoint' : False,
    'checkpoint_file_folder' : './models/default_model/',
    'front_end_input_vectors_dimension' : 80,
    'pooling_input_output_dimension' : 64,
    'training_random_crop_secs' : 2.0,
    'evaluation_random_crop_secs' : 2.0,
    'sample_rate': 16000,
    # 'normalization' : 'cmn',
    'num_workers' : 4,
    'front_end' : 'VGG',
    'vgg_n_blocks' : 3,
    'vgg_channels' : [128, 256, 512],
    'seq_to_seq_method' : 'SelfAttention',
    'seq_to_one_method' : 'StatisticalPooling',
    'training_augmentation_prob' : 0.75,
    'evaluation_augmentation_prob' : 0,
    # 'bottleneck_drop_out' : 0.0,
    # 'embedding_size' : 400,
    # 'scaling_factor' : 30.0,
    # 'margin_factor' : 0.4,
    'optimizer' : 'adam',
    'learning_rate' : 0.0001,
    'weight_decay' : 0.001,
    # 'verbose' : False,
    'number_classes' : 10, # FIX
    'use_weights_and_biases' : False,
}

