LABELS_TO_IDS = {
    "n": 0,
    "x": 1,
    "h": 2,
    "a": 3,
    "c": 4,
    "s": 5,
    "u": 6,
    "d": 7,
    "o": 8,
    "f": 9,
}

TRAIN_DEFAULT_SETTINGS = {
    'train_labels_path' : './labels/training_labels.tsv',
    'validation_labels_path' : './labels/development_labels.tsv',
    'model_output_folder' : './models/',
    'log_file_folder' : './logs/train/',
    'sample_rate': 16000,
    'training_random_crop_secs' : 2.0,
    'evaluation_random_crop_secs' : 2.0,
    'num_workers' : 0,
    'training_augmentation_prob' : 0.75,
    'evaluation_augmentation_prob' : 0,
    'augmentation_window_size_secs' : 2.0,
    'feature_extractor': 'Spectrogram',
    'feature_extractor_output_vectors_dimension' : 80,
    'front_end' : 'Resnet34',
    'adapter_output_vectors_dimension' : 64,
    'seq_to_seq_method' : 'SelfAttention',
    'seq_to_one_method' : 'StatisticalPooling',
    'number_classes' : 10,
    'max_epochs' : 100,
    'training_batch_size' : 64,
    'evaluation_batch_size' : 1,
    'eval_and_save_best_model_every' : 1000,
    'print_training_info_every' : 100,
    'early_stopping' : 25,
    'load_checkpoint' : False,
    'optimizer' : 'adam',
    'learning_rate' : 0.0001,
    'weight_decay' : 0.001,
    'update_optimizer_every' : 10,
    'use_weights_and_biases' : False,
}

